# File       : example_dut.py
# Author     : automatically generated by picker
# Date       : 2025-12-15 20:01:23
# Description: Example usage of adder_trans DUT class
#              This demonstrates pin-level interface for UVM transaction testing
# Version    : v0.1

# Import from the package
from adder_trans_pkg.adder_trans_xagent import *


def monitor_callback(message):
    """
    Example callback function that gets called after monitor updates.
    This demonstrates how to track and respond to state changes.
    """
    sequence = adder_trans(message)
    print(f"  [Monitor Update] {sequence.a.value} + {sequence.b.value} + cin -> {sequence.sum.value} with carry {sequence.cout.value}")


if __name__ == "__main__":
    
    # Initialize Agent
    agent = Agent(send_port="adder_trans", 
                  receive_port="adder_trans",
                  receive_function=monitor_callback)
                  
    agent.run(100)
    
    print(" Example Completed Successfully! ".center(70))
    print("="*70 + "\n")
