# File       : __init__.py
# Author     : automatically generated by picker
# Date       : {{datenow}}
# Description: Python package initialization for {{pkgName}}
# Version    : {{version}}

"""
{{pkgName}} Python Package

This package provides UVM transaction-based communication{% if length(transactions) > 0 %} for multi-transaction testing{% endif %}.

Components:
    - {{className}}_xagent: UVM Agent and transaction classes
{% if length(transactions) > 0 -%}
    - {{className}}: Unified DUT abstraction with pin-level interface
{% else -%}
    - {{className}}: DUT abstraction with pin-level interface
{% endif -%}
"""

__version__ = "{{version}}"
__all__ = ["{{className}}_xagent", "{{className}}"]

# Import main components for easier access
try:
{% if length(transactions) > 0 -%}
    # Multi-transaction mode
    from .{{className}}_xagent import UnifiedAgent
    from .{{className}} import DUT{{className}}
{% else -%}
    # Single transaction mode
    from .{{className}}_xagent import Agent, {{className}}
    from .{{className}} import DUT{{className}}
{% endif -%}
except ImportError as e:
    # Handle import errors gracefully during package installation
    import warnings
    warnings.warn(f"Could not import all components: {e}")


