# File       : __init__.py
# Author     : automatically generated by picker
# Date       : {{datenow}}
# Description: Python package initialization for DUT{{className}}
# Version    : {{version}}

"""
DUT{{className}} Python Package

This package provides UVM transaction-based communication and DUT abstraction
for {{className}} transaction testing.

Components:
    - {{className}}_xagent: UVM Agent and transaction classes
    - DUT{{className}}: High-level DUT abstraction with pin-level interface
"""

__version__ = "{{version}}"
__all__ = ["{{className}}_xagent", "DUT{{className}}"]

# Import main components for easier access
try:
    from .{{className}}_xagent import Agent, {{className}}
    from .DUT{{className}} import DUT{{className}}
except ImportError as e:
    # Handle import errors gracefully during package installation
    import warnings
    warnings.warn(f"Could not import all components: {e}")
