# File       : example.py
# Author     : automatically generated by picker
# Date       : {{datenow}}
# Description: Example usage of {{className}} Agent
# Version    : {{version}}

from {{pkgName}} import Agent{% for trans in transactions %}, {{trans.name}}{% endfor %}
import random


def create_agent(monitor_callback=None):
    """Create pre-configured agent (transactions auto-registered by default)."""
    return Agent(monitor_callback=monitor_callback)


if __name__ == "__main__":
    print("="*70)
    print(" {{className}} Usage Example ".center(70))
    print("="*70 + "\n")

    # ========================================================================
    # Example 1: Basic Usage (Simplest)
    # ========================================================================
    print("-" * 70)
    print("Example 1: Basic Usage")
    print("-" * 70)

    def monitor_handler(trans_type, trans_obj):
        print(f"[Monitor] {trans_type}: {trans_obj}")

    # Use factory function for quick setup
    agent = create_agent(monitor_callback=monitor_handler)

    # Create and drive transactions
    {%- for trans in transactions %}
    tr = {{trans.name}}()
    {%- for data in trans.variables %}
    tr.{{data.name}}.value = random.randint(0, (1 << {{data.bit_count}}) - 1)
    {%- endfor %}
    agent.drive(tr)
    print(f"Sent: {tr}")
    {% endfor %}
    agent.run(10)


    # ========================================================================
    # Example 3: Batch Processing (Uncomment to use)
    # ========================================================================
    # print("\n" + "-" * 70)
    # print("Example 3: Batch Processing")
    # print("-" * 70)
    #
    # batch_agent = create_agent()
    # # Create multiple transactions and send them
    # for i in range(10):
{%- for trans in transactions %}
    #     tr = {{trans.name}}()
{%- for data in trans.variables %}
    #     tr.{{data.name}}.value = random.randint(0, 0xFF)
{%- endfor %}
    #     batch_agent.drive(tr)
    #     batch_agent.run(1)
{%- endfor %}

    print("\n" + "="*70)
    print(" Done ".center(70))
    print("="*70)
