//==============================================================================//
// File       : example_uvm_dut.sv
// Author     : automatically generated by picker
// Date       : {{datenow}}
// Description: UVM testbench for DUT{{className}} example
//              This is a simplified testbench that receives transactions from
//              Python DUT class. It only has a driver (no monitor) since 
//              the communication is unidirectional (Python → UVM).
// Version    : {{version}}
//==============================================================================//
import uvm_pkg::*;
import uvmc_pkg::*;
`include "../../{{filepath}}"
`include "../{{className}}_xagent.sv"

interface example_interface(input clk, input rst_n);
    // Add your DUT interface signals here if needed
    // For this example, we just verify that transactions are received
endinterface //example_interface


class example_driver extends {{className}}_xdriver;
    `uvm_component_utils(example_driver);
    int transaction_count;
    
    function new (string name = "example_driver", uvm_component parent = null);
        super.new(name,parent);
        transaction_count = 0;
    endfunction

    virtual function void build_phase(uvm_phase phase);
        super.build_phase(phase);
    endfunction

    function sequence_receive({{className}} tr);
        transaction_count++;
        `uvm_info("example_driver", $sformatf("Received transaction #%0d from Python:\n%s", 
                                               transaction_count, tr.sprint()), UVM_LOW)
    endfunction
    
    function void report_phase(uvm_phase phase);
        super.report_phase(phase);
        `uvm_info("example_driver", $sformatf("Total transactions received: %0d", transaction_count), UVM_LOW)
    endfunction
endclass


class example_env extends uvm_env;
    `uvm_component_utils(example_env)
    {{className}}_xagent            xagent;
    {{className}}_xagent_config     xagent_config;
    virtual example_interface       vif;
    
    function new (string name = "example_env", uvm_component parent = null);
        super.new(name,parent);
        xagent_config = new("xagent_config");
        xagent_config.drv_type = example_driver::get_type();
        uvm_config_db#({{className}}_xagent_config)::set(this,"xagent", "{{className}}_xagent_config", xagent_config);
    endfunction

    function void build_phase(uvm_phase phase);
        super.build_phase(phase);
        xagent = {{className}}_xagent::type_id::create("xagent",this);
        if(!uvm_config_db#(virtual example_interface)::get(this,"","vif",vif))
            `uvm_fatal("example_env","virtual interface must be set for vif")
    endfunction

    virtual task main_phase(uvm_phase phase);
        phase.raise_objection(this);
        // Just wait for Python to send transactions
        // Python controls the simulation time via Step() calls
        #10000;  // Wait long enough for Python to complete
        phase.drop_objection(this);
    endtask

endclass


class example_test extends uvm_test;
    `uvm_component_utils(example_test)
    example_env env;
    
    function new (string name = "example_test", uvm_component parent = null);
        super.new(name,parent);
    endfunction

    function void build_phase(uvm_phase phase);
        super.build_phase(phase);
        env = example_env::type_id::create("example_env",this);
    endfunction
endclass


module sv_main;
    logic clk;
    logic rst_n;
    example_interface vif(clk,rst_n);
    
    initial begin
        clk = 0;
        forever begin
            #2
            clk <= ~clk;
        end
    end
    
    initial begin
        rst_n <= 1'b0;
        #10
        rst_n <= 1'b1;
    end
    
    initial begin
        uvm_config_db #(virtual example_interface)::set(null,"uvm_test_top.example_env","vif",vif);
        run_test("example_test");
    end
endmodule
