# File       : example_dut.py
# Author     : automatically generated by picker
# Date       : {{datenow}}
# Description: Example usage of DUT{{className}} class
#              This demonstrates pin-level interface for UVM transaction testing
# Version    : {{version}}

import sys
sys.path.append('../')
from DUT{{className}} import DUT{{className}}

if __name__ == "__main__":
    print("\n" + "="*60)
    print("DUT{{className}} Usage Example")
    print("="*60 + "\n")
    
    # Initialize DUT (this happens after UVM is ready)
    dut = DUT{{className}}()
    print("✓ DUT initialized successfully\n")
    
    # Example: Send multiple transactions
    print("Sending 10 transactions with Step()...")
    for i in range(10):
        # Set field values
        {% for data in variables -%}
        dut.{{data.name}}.xdata.value = i * {{ loop.index1 * 5 }}
        {% endfor %}
        
        print(f"  Transaction {i}: {%for data in variables%}{{data.name}}={dut.{{data.name}}.xdata.value}{%if not loop.is_last%}, {%endif%}{%endfor%}")
        
        # Step simulation to send this transaction
        # Each Step(1) sends the transaction and advances 1 cycle
        dut.Step(1)
    
    # Run additional cycles to let UVM process all transactions
    print("\nRunning 100 more cycles to complete simulation...")
    dut.Step(100)
    
    print("\n" + "="*60)
    print("Example completed successfully!")
    print("="*60)
