//==============================================================================
// File       : picker_uvm_utils_pkg.sv
// Author     : automatically generated by picker
// Description: Common utility package for UVM-Python communication
//              Provides shared serialization/deserialization functions
// Version    : 1.0
//==============================================================================

package picker_uvm_utils_pkg;

    // Maximum field width supported for serialization
    parameter int MAX_FIELD_WIDTH = 2048;

    // Legacy serialize_field for backward compatibility (used by send_transaction)
    // Dynamically appends bytes to the transport_array
    function automatic void serialize_field(
        input bit [MAX_FIELD_WIDTH-1:0] data,
        input int bit_count,
        ref byte unsigned transport_array[]
    );
        int rem_bits = bit_count % 8;
        if(rem_bits != 0) begin
            logic[7:0] byte_buf = 8'b0;
            for(int i = 0; i < rem_bits; i++)
                byte_buf[rem_bits - i - 1] = data[bit_count - 1 - i];
            transport_array = {transport_array, byte_buf};
        end
        for(int i = 0; i < bit_count / 8; i++)
            transport_array = {transport_array, data[(bit_count - 1 - rem_bits - i*8) -: 8]};
    endfunction

    // Optimized serialize_field that writes directly to pre-allocated array
    // Recommended for performance-critical paths (Monitor send)
    function automatic void serialize_field_inplace(
        input bit [MAX_FIELD_WIDTH-1:0] data,
        input int bit_count,
        ref byte unsigned transport_array[],
        input int start_offset
    );
        int offset = start_offset;
        int rem_bits = bit_count % 8;
        logic[7:0] byte_buf;

        // Handle non-byte-aligned bits
        if(rem_bits != 0) begin
            byte_buf = 8'b0;
            for(int i = 0; i < rem_bits; i++)
                byte_buf[rem_bits - i - 1] = data[bit_count - 1 - i];
            transport_array[offset] = byte_buf;
            offset++;
        end

        // Write full bytes
        for(int i = 0; i < bit_count / 8; i++) begin
            byte_buf = 8'b0;
            for(int j = 0; j < 8; j++)
                byte_buf[7-j] = data[bit_count - 1 - rem_bits - i*8 - j];
            transport_array[offset] = byte_buf;
            offset++;
        end
    endfunction

    // Deserialize field from byte array to bit vector
    // Recommended for performance-critical paths (Driver receive)
    function automatic bit[MAX_FIELD_WIDTH-1:0] deserialize_field(
        input byte unsigned transport_array[],
        input int start_offset,
        input int bit_count
    );
        bit[MAX_FIELD_WIDTH-1:0] result;
        int byte_count = (bit_count + 7) / 8;
        int rem_bits = bit_count % 8;
        int offset = start_offset;

        result = '0;

        // Handle non-byte-aligned leading bits
        if(rem_bits != 0) begin
            for(int i = 0; i < rem_bits; i++)
                result[bit_count - 1 - i] = transport_array[offset][rem_bits - i - 1];
            offset++;
        end

        // Read full bytes
        for(int i = 0; i < bit_count / 8; i++) begin
            for(int j = 0; j < 8; j++)
                result[bit_count - 1 - rem_bits - i*8 - j] = transport_array[offset][7-j];
            offset++;
        end

        return result;
    endfunction

endpackage : picker_uvm_utils_pkg
