# File       : example_dut.py
# Author     : automatically generated by picker
# Date       : 2025-12-15 19:01:04
# Description: Example usage of adder_trans DUT class
#              This demonstrates pin-level interface for UVM transaction testing
# Version    : v0.1

# Import from the package
from adder_trans_pkg.adder_trans_xagent import *
import random


if __name__ == "__main__":
    
    # Initialize DUT
    print("Initializing DUT...")
    #dut = DUTadder_trans()
    agent = Agent(send_port="adder_trans", 
                  receive_port="adder_trans",
                  receive_function=lambda msg: print(msg))
    print("✓ DUT initialized successfully\n")
    
    
    # Example 1: Basic pin manipulation with Step
    print("-" * 70)
    print("Example 1: Basic Pin Manipulation")
    print("-" * 70)
    for i in range(5):
        # Set field values using clean interface: dut.field.value
        tr = adder_trans()
        tr.a.value = i * 10
        tr.b.value = i * 20
        tr.cin.value = random.randint(1, 10)
        tr.sum.value = i * 30
        tr.cout.value = random.randint(1, 10)
        tr.send(agent)

        agent.run(1)
        
        # Show values before Step
        # print(f"Cycle {i:2d} - Before Step: {tr}")

    